// The atomic marketplace only operates on the transfer-capable Music NFT v2.
// Do not fall back to NFT_CONTRACT_ID: legacy deployments cannot be escrowed.
export const MUSIC_NFT_V2_CONTRACT_ID =
  process.env.MUSIC_NFT_V2_CONTRACT_ID ||
  'CAUBEZ6RC7PWP47FZVBKHPVQ6BRS57FPVPZELZFMVINFNZKOEY6L3MXD';

export const MARKETPLACE_CONTRACT_ID =
  process.env.MARKETPLACE_CONTRACT_ID ||
  'CBWB4TRYIMG5KQSI6HIKRZIUTYHIGNJ4EHUA4PTO6R3TJSHBXCDB56HE';

export const MUSIC_PURCHASE_CONTRACT_ID =
  process.env.MUSIC_PURCHASE_CONTRACT_ID ||
  'CD4FPDV7VCCVKQBIKU6MBVUPJFW6KMRMB5H4JT6ENR27QWKIPDYQKE5H';

export const PAYMENT_ASSET_CONTRACT_ID =
  process.env.PAYMENT_ASSET_CONTRACT_ID ||
  'CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC';
