'use client';
import { useEffect, useState } from 'react';
import { ListedTrack, PurchaseModal } from './PurchaseModal';
const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000';
export function MarketplaceDrops() {
  const [tracks, setTracks] = useState<ListedTrack[]>([]); const [selected, setSelected] = useState<ListedTrack | null>(null);
  const load = async () => { try { const response = await fetch(`${API_URL}/api/music?listed=true&limit=6`); const json = await response.json(); if (response.ok) setTracks(json.data || []); } catch {} };
  useEffect(() => { load(); }, []);
  return <section className="page-shell pb-16 sm:pb-24"><div className="mb-8 flex items-end justify-between gap-4"><div><p className="eyebrow mb-2">Fresh listings</p><h2 className="display text-4xl sm:text-5xl">AVAILABLE DROPS</h2></div><span className="hidden text-sm text-white/55 sm:block">Settled atomically on Stellar</span></div>{tracks.length ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{tracks.map((track, index) => <article key={track._id} className="card group overflow-hidden p-5"><div className={`flex aspect-[1.4] items-center justify-center rounded-2xl bg-gradient-to-br ${index % 2 ? 'from-[#5865f2] to-[#ec48bd]' : 'from-[#ec48bd] to-[#6c55e8]'} text-7xl transition-transform duration-300 group-hover:scale-[1.02]`}>♫</div><p className="mt-5 text-xs font-bold tracking-widest text-[#35ed7e]">MUSIC NFT #{track.tokenId}</p><h3 className="mt-2 text-xl font-bold">{track.name}</h3><p className="text-sm text-white/60">{track.artist}</p><div className="mt-5 flex items-center justify-between"><span className="font-bold text-[#35ed7e]">{track.listing.price} stroops</span><button className="btn-primary px-4 py-2 text-sm" onClick={() => setSelected(track)}>Buy</button></div></article>)}</div> : <div className="card rounded-[32px] p-8 text-center text-white/65">No active drops yet. New music listings will land here.</div>}{selected && <PurchaseModal track={selected} onClose={() => setSelected(null)} onPurchased={() => { setSelected(null); load(); }} />}</section>;
}
