'use client';

import { useState } from 'react';
import { useWallet } from '@/hooks/useWallet';

export interface ListedTrack { _id: string; tokenId: number; name: string; artist: string; owner: string; listing: { listingId: string; price: string; active: boolean }; }
interface PurchaseResponse { success: boolean; transactionHash: string; ledger?: number; status: string; buyer: string; seller: string; listingId: string; contractId: string; explorerUrl: string; error?: { message: string }; }
const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000';

export function PurchaseModal({ track, onClose, onPurchased }: { track: ListedTrack; onClose: () => void; onPurchased: () => void }) {
  const { address, isConnected, connect, signTransaction } = useWallet();
  const [submitting, setSubmitting] = useState(false); const [error, setError] = useState(''); const [result, setResult] = useState<PurchaseResponse | null>(null);
  const buy = async () => { if (!isConnected || !address) { await connect(); return; } setSubmitting(true); setError(''); try {
    const buildResponse = await fetch(`${API_URL}/api/purchase/build`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ listingId: track.listing.listingId, buyer: address, offeredPrice: track.listing.price }) });
    const build = await buildResponse.json(); if (!buildResponse.ok || !build.success) throw new Error(build.error?.message || 'Unable to prepare purchase');
    const signedTxXDR = await signTransaction(build.data.transactionXDR);
    const submitResponse = await fetch(`${API_URL}/api/purchase`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ signedTxXDR, listingId: track.listing.listingId, buyer: address, offeredPrice: track.listing.price }) });
    const purchase: PurchaseResponse = await submitResponse.json(); if (!submitResponse.ok || !purchase.success) throw new Error(purchase.error?.message || 'Purchase failed'); setResult(purchase); onPurchased();
  } catch (err: any) { setError(err.message || 'Purchase failed'); } finally { setSubmitting(false); } };
  const short = (value: string) => `${value.slice(0, 8)}…${value.slice(-6)}`;
  return <div className="fixed inset-0 z-[60] flex items-end bg-[#050720]/80 p-3 backdrop-blur-sm sm:items-center sm:justify-center" role="dialog" aria-modal="true"><div className="w-full max-w-lg rounded-[32px] border border-white/15 bg-[#1e2353] p-6 shadow-2xl sm:p-8">{result ? <><div className="flex h-14 w-14 items-center justify-center rounded-full bg-[#35ed7e] text-3xl text-[#0a0d3a]">✓</div><h2 className="display mt-5 text-3xl">PURCHASE SUCCESSFUL</h2><p className="mt-2 text-white/70">{track.name} is now in your vault.</p><dl className="mt-6 space-y-3 rounded-2xl bg-[#0a0d3a] p-4 text-sm"><div className="flex justify-between gap-3"><dt className="text-white/55">Transaction Hash</dt><dd className="font-mono text-right">{short(result.transactionHash)}</dd></div><div className="flex justify-between gap-3"><dt className="text-white/55">Contract ID</dt><dd className="font-mono text-right">{short(result.contractId)}</dd></div><div className="flex justify-between gap-3"><dt className="text-white/55">New Owner</dt><dd className="font-mono text-right">{short(result.buyer)}</dd></div><div className="flex justify-between gap-3"><dt className="text-white/55">Price Paid</dt><dd>{track.listing.price} stroops</dd></div><div className="flex justify-between gap-3"><dt className="text-white/55">Ledger</dt><dd>{result.ledger ?? 'Confirmed'}</dd></div></dl><div className="mt-6 grid grid-cols-2 gap-3"><button onClick={() => navigator.clipboard.writeText(result.transactionHash)} className="btn-primary">Copy hash</button><a className="btn-secondary" href={result.explorerUrl} target="_blank" rel="noreferrer">Open Stellar Expert ↗</a></div><button onClick={onClose} className="mt-3 w-full py-2 text-sm font-bold text-white/65 hover:text-white">Done</button></> : <><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">Confirm purchase</p><h2 className="display mt-2 text-3xl">MAKE IT YOURS.</h2></div><button onClick={onClose} className="text-2xl text-white/60 hover:text-white" aria-label="Close">×</button></div><div className="mt-6 rounded-2xl bg-[#0a0d3a] p-5"><p className="font-bold">{track.name}</p><p className="mt-1 text-sm text-white/60">by {track.artist}</p><div className="mt-5 flex items-end justify-between"><span className="text-sm text-white/55">Listed price</span><strong className="text-xl text-[#35ed7e]">{track.listing.price} stroops</strong></div></div>{error && <p className="mt-4 rounded-xl bg-red-500/15 p-3 text-sm text-red-200">{error}</p>}<button onClick={buy} disabled={submitting} className="btn-accent mt-6 w-full text-lg">{submitting ? 'Confirming on Stellar…' : isConnected ? 'Confirm & buy' : 'Connect Freighter'}</button><p className="mt-3 text-center text-xs text-white/45">The NFT and payment settle in one Soroban transaction.</p></>}</div></div>;
}
